# Types of numpy arrays

There are some ways to quickly create numpy arrays
* `linspace()`
* `arange()`
* `zeros()`
* `ones()`
* `empty()`

In [1]:
import numpy

# `zeros()`

`zeros()` is the numpy array method to create array elements of value 0 (of int type), 0. (for decimal type) and '' (for string type)

In [2]:
testing1=numpy.zeros(3)
print(testing1)
print('-'*66)
testing2=numpy.zeros((3,3),dtype=str)
print(testing2)

[0. 0. 0.]
------------------------------------------------------------------
[['' '' '']
 ['' '' '']
 ['' '' '']]


# `ones()`

`ones()` creates numpy array elements of value 1 (of int type), 1. (in float type) and '1' in string type
it has the same parameters as of `zeros()`

In [3]:
testing3=numpy.ones(6,dtype=str)
print(testing3)
print('-'*66)
testing4=numpy.ones((3,3,3))
print(testing4)

['1' '1' '1' '1' '1' '1']
------------------------------------------------------------------
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# `arange()`

`arange()` is similar to the `range()` it is of form `arange(start,stop,step=1,dtype)` it accepts int values for the start, stop and step and note that dtype can't be of `str` type

In [4]:
testing5=numpy.arange(2,5)
print(testing5)
print('-'*66)
testing6=numpy.arange(6,67,2,dtype=float)
print(testing6)

[2 3 4]
------------------------------------------------------------------
[ 6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.
 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66.]


# `empty()`

`empty()` creates an array of some junk values it has paramaeters of shape and dtype but for string type it has '' value

In [5]:
testing7=numpy.empty((3,3))
print(testing7)
print('-'*66)
testing8=numpy.empty((3,3),dtype=str)
print(testing8)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 4.09e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
------------------------------------------------------------------
[['' '' '']
 ['' '' '']
 ['' '' '']]


# `linspace()`
`linspace(start,stop,num,endpoint,retstep=False,dtype,axis)` 
* start and stop denotes the starting pt. of the array and ending pt. of the aray respec. can be of types `int` or `float` or `iterative containers like list() or tuple() etc...`
* num denotes the number of the elements in the array  (default=50)
* retstep if True returns the tuple of numpy array and the step size (default=`False`)
* dtype for the type of the array (default=`float`)
* endpoint denotes whether to include endpoint in the array or not (default=`True`)
* axis is used whenever start o rstop is of iterative type it specifies whether to store nanswer in rows (value=1) or in columns (value=0 default)

In [6]:
testing9=numpy.linspace(2.0,3.0,num=6,dtype=str)
print(testing9) # includes the end point
print('-'*66)
testing10=numpy.linspace(2.0,3.0,num=6,endpoint=False,dtype=float)
print(testing10) # doesn't include end point 
print('-'*66)
print(type(testing10))
print('-'*66)
testing11=numpy.linspace(2.0,6.0,num=6,endpoint=True,retstep=True,dtype=int)
print(testing11)

['2.0' '2.2' '2.4' '2.6' '2.8' '3.0']
------------------------------------------------------------------
[2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333]
------------------------------------------------------------------
<class 'numpy.ndarray'>
------------------------------------------------------------------
(array([2, 2, 3, 4, 5, 6]), 0.8)


## 2d arrays with `linspace()`

we can create 2 D arrays with `linspace()` for that start and stop must be of iterative type like `list()` or `tuple()`,etc..

In [7]:
testing12=numpy.linspace([1,2],[5,6],num=6)
# element indexes are lined like all 0s ae linked and all 1s are linked
print(testing12)
print('-'*66)
try:
    testing13=numpy.linspace([1,2,3],[7,8],num=10)
    print(testing13)
except:
    # note here all the iterative type of start and stop must have the same size
    print('error')
print('-'*66)
try:
    testing14=numpy.linspace([1,2],['3','4'],num=10)
    print(testing14)
except:
    print('all the elements in the start and stop must be of same type')

[[1.  2. ]
 [1.8 2.8]
 [2.6 3.6]
 [3.4 4.4]
 [4.2 5.2]
 [5.  6. ]]
------------------------------------------------------------------
error
------------------------------------------------------------------
all the elements in the start and stop must be of same type


In [8]:
testing15= numpy.linspace(start=1, stop=[5, 6, 14, 24], num=5)
print(testing15)
# if one has single type then they are converted to iterative type of size of another (among start and stop)

[[ 1.    1.    1.    1.  ]
 [ 2.    2.25  4.25  6.75]
 [ 3.    3.5   7.5  12.5 ]
 [ 4.    4.75 10.75 18.25]
 [ 5.    6.   14.   24.  ]]


In [9]:
# here we can see the answers for each element corresponds through columns (axis=0)(default)
testing16= numpy.linspace([1,2],[5,6],num=6,axis=0)
print(testing16)
print('-'*66)
# here answers for each element corresponds through rows (axis=1)
testing17=numpy.linspace([1,2],[5,6],num=6,axis=1)
print(testing17)

[[1.  2. ]
 [1.8 2.8]
 [2.6 3.6]
 [3.4 4.4]
 [4.2 5.2]
 [5.  6. ]]
------------------------------------------------------------------
[[1.  1.8 2.6 3.4 4.2 5. ]
 [2.  2.8 3.6 4.4 5.2 6. ]]
