# Indexing and Slicing

with indexing we can access the elements in the array (particular element or range of elements).



# Single Dimensional Arrays

Indexing and Slicing for 1-d numpy arrays follows the same pattern as that of Lists and Tuples.  
`[Start:Stop:Step]`

In [1]:
import numpy

In [2]:
testing1=numpy.arange(20)
print(testing1)
print(66*'-')
print(testing1[2])
print(66*'-')
print(testing1[1:6])
print(66*'-')
print(testing1[5:])
print(66*'-')
print(testing1[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------------------------------------------------------------
2
------------------------------------------------------------------
[1 2 3 4 5]
------------------------------------------------------------------
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------------------------------------------------------------
[ 0  2  4  6  8 10 12 14 16 18]


# Multi Dimensional Arrays

In [3]:
testing2=numpy.arange(36).reshape(6,6)
print(testing2)
print(69*'-')


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
