# Operators

    Operators that can do certain operators when used over multiple numpy.arrays. But those multiple arrays must have the same shape.

In [10]:
import numpy

# plus(+), minus(-), multiplication(*), division(/), modulo(%), interger division(truediv)(//)

In [11]:
testing1=numpy.arange(6)
testing2=numpy.arange(6,12)
print(testing1+testing2)
print('-'*66)
testing3=numpy.arange(9)
testing3=testing3.reshape(3,3)
print(testing3)
print('-'*66)
testing4=numpy.arange(9,18)
testing4=testing4.reshape(3,3)
print(testing4)
print('-'*66)
print(testing3-testing4)

[ 6  8 10 12 14 16]
------------------------------------------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------------------------------------------------
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
------------------------------------------------------------------
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [12]:
testing5=numpy.zeros((3,3))
testing5=testing5+6
print(testing5)
print('-'*66)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
------------------------------------------------------------------
