In [2]:
import numpy

In [3]:
# TODO: arrays with zeros are commonly used 
a=numpy.zeros(2) # set() is one of the parameter here
a

array([0., 0.])

In [4]:
# TODO: to create the numpy of n dimensions use sets
a=numpy.zeros((2,6))
a


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
a=numpy.zeros((6,6),str)
a

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [8]:
a=numpy.zeros((3,3),int)
a


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])