In [1]:
import numpy

a = numpy.array(
    [
     [
      1, 2, 3
     ],
     [
      4, 5, 6
     ],
     [
      7, 8, 9
     ]
    ]
)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print("# dimensions")
print(a.ndim) 

print("# number of elements")
print(a.size)

print("# number of bytes")
print(a.nbytes)

print("# bytes per eleemnt")
print(a.itemsize)

print("# shape (elements in each dimemnsions)")
print(a.shape)

# dimensions
2
# number of elements
9
# number of bytes
72
# bytes per eleemnt
8
# shape (elements in each dimemnsions)
(3, 3)
